name: "Drako0812's Homepage"
title: "Drako0812's Homepage"
author: Drew Wibbenmeyer
email: drako0812@gmail.com
description: Drako0812's personal website.
github_username: drako0812
twitter_username: drako0812
youtube_username: channel/UCPzSCdLttX_hSe0TjiJ5Sgg

markdown: kramdown
permalink: /blog/:year/:month/:day/:title
gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-mentions
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
header_pages:
  - projects.md
  - blog/index.html
  - world-of-vidras/index.md

show_excerpts: true
