name: "Drako0812's Homepage"
author: Drew Wibbenmeyer
email: drako0812@gmail.com
description: Drako0812's personal website.
github_username: drako0812

markdown: kramdown
permalink: /blog/:year/:month/:day/:title
gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-mentions
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
